version: '3'

services:
  db:
    image: mysql:5.6
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: python
      MYSQL_DATABASE: bizdb
    env_file:
      - ~/.mysqlrc
    volumes:
      - "/var/lib/mysql/data:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 13306:8080
